<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Leave Requests Export</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 11px;
            color: #1e293b;
            background: #fff;
            padding: 24px;
        }

        /* ── Header ── */
        .report-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 20px;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 12px;
        }

        .report-title {
            font-size: 20px;
            font-weight: 700;
            color: #1e40af;
        }

        .report-meta {
            font-size: 10px;
            color: #64748b;
            text-align: right;
            line-height: 1.6;
        }

        /* ── Summary pills ── */
        .summary-row {
            display: flex;
            gap: 10px;
            margin-bottom: 18px;
        }

        .summary-pill {
            padding: 6px 14px;
            border-radius: 20px;
            font-size: 10px;
            font-weight: 600;
        }

        .pill-blue {
            background: #dbeafe;
            color: #1e40af;
        }

        .pill-green {
            background: #dcfce7;
            color: #166534;
        }

        .pill-yellow {
            background: #fef9c3;
            color: #854d0e;
        }

        .pill-red {
            background: #fee2e2;
            color: #991b1b;
        }

        .pill-gray {
            background: #f1f5f9;
            color: #475569;
        }

        /* ── Table ── */
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 10px;
        }

        thead tr {
            background: #1e40af;
            color: #fff;
        }

        thead th {
            padding: 8px 7px;
            text-align: left;
            font-weight: 600;
            white-space: nowrap;
        }

        tbody tr:nth-child(even) {
            background: #f8fafc;
        }

        tbody tr:hover {
            background: #eff6ff;
        }

        tbody td {
            padding: 7px 7px;
            border-bottom: 1px solid #e2e8f0;
            vertical-align: middle;
        }

        /* ── Status badges ── */
        .badge {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 10px;
            font-size: 9px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.4px;
        }

        .badge-approved {
            background: #dcfce7;
            color: #166534;
        }

        .badge-pending {
            background: #fef9c3;
            color: #854d0e;
        }

        .badge-rejected {
            background: #fee2e2;
            color: #991b1b;
        }

        .badge-cancelled {
            background: #f1f5f9;
            color: #475569;
        }

        /* ── Leave-type chips ── */
        .type-chip {
            display: inline-block;
            padding: 2px 7px;
            border-radius: 4px;
            font-size: 9px;
            font-weight: 600;
            background: #e0e7ff;
            color: #3730a3;
        }

        /* ── Footer ── */
        .report-footer {
            margin-top: 20px;
            text-align: center;
            font-size: 9px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
        }
    </style>
</head>

<body>

    <div class="report-header">
        <div>
            <div class="report-title">Leave Requests Report</div>
            <div style="font-size:11px; color:#64748b; margin-top:4px;">
                Filter: <strong>{{ ucfirst($status) }}</strong> &nbsp;|&nbsp;
                Total records: <strong>{{ $leaves->count() }}</strong>
            </div>
        </div>
        <div class="report-meta">
            Exported on: {{ $exported }}<br>
            Generated by HR System
        </div>
    </div>

    @php
    $countApproved = $leaves->where('status', 'approved')->count();
    $countPending = $leaves->where('status', 'pending')->count();
    $countRejected = $leaves->where('status', 'rejected')->count();
    $countCancelled = $leaves->where('status', 'cancelled')->count();
    @endphp

    <div class="summary-row">
        <span class="summary-pill pill-blue">Total: {{ $leaves->count() }}</span>
        <span class="summary-pill pill-green">Approved: {{ $countApproved }}</span>
        <span class="summary-pill pill-yellow">Pending: {{ $countPending }}</span>
        <span class="summary-pill pill-red">Rejected: {{ $countRejected }}</span>
        <span class="summary-pill pill-gray">Cancelled: {{ $countCancelled }}</span>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Employee</th>
                <th>Leave Type</th>
                <th>From</th>
                <th>To</th>
                <th>Days</th>
                <th>Duration</th>
                <th>Status</th>
                <th>Reason</th>
                <th>Contact</th>
                <th>Reviewed By</th>
                <th>Reviewed At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($leaves as $i => $leave)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td><strong>{{ $leave->user->name ?? '-' }}</strong></td>
                <td><span class="type-chip">{{ ucfirst($leave->leave_type) }}</span></td>
                <td>{{ $leave->from_date->format('d M Y') }}</td>
                <td>{{ $leave->to_date->format('d M Y') }}</td>
                <td><strong>{{ $leave->total_days }}</strong></td>
                <td>{{ ucfirst($leave->duration ?? 'Full') }}</td>
                <td>
                    <span class="badge badge-{{ $leave->status }}">
                        {{ ucfirst($leave->status) }}
                    </span>
                </td>
                <td>{{ Str::limit($leave->reason, 40) }}</td>
                <td>{{ $leave->contact_phone ?? $leave->contact_email ?? '-' }}</td>
                <td>{{ $leave->reviewer->name ?? '-' }}</td>
                <td>{{ $leave->reviewed_at ? $leave->reviewed_at->format('d M Y') : '-' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="12" style="text-align:center; padding:20px; color:#94a3b8;">
                    No leave requests found.
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="report-footer">
        This report was automatically generated &mdash; HR Leave Management System &mdash; {{ $exported }}
    </div>

</body>

</html>